export const PERSONAL_CSS = String.raw`
/* A quiet, consistent workspace shared by the home, chat and transfer views. */
:root{
  --px-bg:#101016;--px-bg-soft:#17171f;--px-surface:#1b1b25;--px-surface-2:#23232f;--px-surface-3:#2c2c39;
  --px-glass:rgba(23,23,31,.94);--px-text:#f4f2fc;--px-text-2:#bebccb;--px-muted:#9b98ac;--px-dim:#8b879e;
  --px-acc:#b3a1ff;--px-acc-2:#9478ed;--px-acc-soft:rgba(179,161,255,.12);--px-line-acc:rgba(179,161,255,.24);
  --px-line:rgba(210,204,241,.09);--px-line-2:rgba(210,204,241,.16);--px-nav:246px;--px-head:72px;
  --studio-hero:#222130;--studio-tint:#302b42;--studio-mint:#a5ddc7;--studio-amber:#f2cf91;--studio-coral:#eeb5ab;
  --grad:linear-gradient(115deg,#aa90f4,#8e75d5);--glass-border:var(--line);--glass-border-hover:var(--acc-line);
}
html[data-px-theme="light"]{
  --px-bg:#f7f6fb;--px-bg-soft:#fff;--px-surface:#fff;--px-surface-2:#f0edf8;--px-surface-3:#e8e3f3;
  --px-text:#282239;--px-text-2:#5e566e;--px-muted:#746a84;--px-dim:#81758f;--px-glass:rgba(255,255,255,.94);
  --px-acc:#6e4eb5;--px-acc-2:#8863d5;--px-acc-soft:rgba(110,78,181,.08);--px-line-acc:rgba(110,78,181,.22);
  --px-line:rgba(77,54,116,.1);--px-line-2:rgba(77,54,116,.17);--studio-hero:#eee8fa;--studio-tint:#e4dcf5;
  --studio-mint:#357861;--studio-amber:#956022;--studio-coral:#a55343;
  --grad:linear-gradient(115deg,#7d5bc5,#604098);--glass-border:var(--line);
}
body::before{display:none}button:disabled{cursor:wait;opacity:.55}button{transition:background .18s,color .18s,border-color .18s,transform .18s}
.px-icon{display:inline-block;vertical-align:middle;flex-shrink:0}button .px-icon{pointer-events:none}
.side{background:var(--bg2);border-color:var(--line);backdrop-filter:none}.side-h{padding:10px 22px 23px;border:0;gap:11px}
.logo{background:var(--acc);color:var(--bg);box-shadow:none;border-radius:13px;width:39px;height:39px;font-size:23px}
.side-h .nm{letter-spacing:-.5px;font-size:16px;direction:ltr}.side-h .nm span{font-weight:450;color:var(--text2)}.side-h .tg{font-size:10px;color:var(--muted);margin-top:5px}
.side-new{display:flex;align-items:center;gap:10px;margin:0 16px 16px;padding:12px 14px;border:1px solid var(--acc-line);border-radius:13px;background:var(--acc-soft);color:var(--acc);font-weight:650;font-size:12px}.side-new:hover{background:var(--surface3)}.side-plus{margin-inline-start:auto;font-size:19px}
.side-s{padding:0 14px}.navg{margin-bottom:18px}.navg-t{font-size:10px;font-weight:500;color:var(--muted);letter-spacing:0;padding:6px 11px 8px}
.navi{padding:9px 11px;font-size:12px;border:1px solid transparent;min-height:42px;margin-bottom:3px;gap:11px}.navi i{display:flex;align-items:center;justify-content:center}.navi.on{color:var(--acc);border-color:var(--acc-line);background:var(--acc-soft)}.navi:hover{background:var(--surface2)}
.side-f{padding:12px 14px}.uchip{background:var(--surface);border-color:var(--line)}.uchip:hover{background:var(--surface2)}
.head{background:var(--bg);border-color:var(--line);padding-inline:30px;height:calc(var(--head) + var(--safet));backdrop-filter:blur(16px)}.head-t h1{font-size:14px;font-weight:650}.head-t .sub{font-size:10px;margin-top:5px}
.head .btn-icon{background:transparent;border-color:transparent;width:36px;height:36px}.head .btn-icon:hover{background:var(--surface2)}
.main{padding:30px;scrollbar-gutter:stable}.main #view{max-width:1260px;margin-inline:auto}.head-actions{gap:7px}.card{box-shadow:none;border-color:var(--line);backdrop-filter:none;border-radius:18px}.card:hover{border-color:var(--line2)}
.tabbar{background:var(--glass);border-color:var(--line)}.tabi.on{color:var(--acc)}.tabi i{display:flex;align-items:center;justify-content:center}.tabi.on::after{background:var(--acc);box-shadow:none}
.btn.pri{background:var(--grad);box-shadow:none}.btn.sec,.btn.gho,.ibtn,.btn-icon{background:var(--surface);border-color:var(--line);color:var(--text2)}.btn.gho:hover,.btn.sec:hover,.ibtn:hover{background:var(--surface2);color:var(--text)}
.input,.select,.fld input,.fld select,.fld textarea,.picker{background:var(--bg2);border-color:var(--line2);color:var(--text)}.pick.on,.citem.on{color:var(--acc)}.ans-b{background:var(--bg2)}.tbl th{background:var(--bg2)}.tabs{background:var(--bg2)}.tst,.sheet,.modal-sheet{background:var(--surface);border-color:var(--line2);color:var(--text)}.sheet-handle{background:var(--line2)}
.boot{background:var(--bg)}.boot-logo{background:var(--acc);color:var(--bg);box-shadow:none;animation:none}.boot-t{color:var(--text);background:none;-webkit-text-fill-color:var(--text)}.boot-glow{background:radial-gradient(circle,var(--acc-soft),transparent 65%);filter:blur(30px)}
.auth-gate h1{font-size:23px;font-weight:750}.auth-gate p{max-width:330px;color:var(--text2);font-size:13px;line-height:1.9}
.studio-home{max-width:1080px;margin:auto}.studio-greeting{display:flex;justify-content:space-between;align-items:center;gap:15px;margin-bottom:26px}.studio-greeting .uav{border-radius:50%;color:var(--acc);background:var(--acc-soft);border-color:transparent}
.studio-eyebrow{display:block;font-size:10px;letter-spacing:.2px;color:var(--muted);margin-bottom:4px}.studio-greeting h2{font-weight:600;font-size:16px;line-height:1.6}.hello-dot{color:var(--acc);margin-inline-start:3px}.studio-date{font-size:11px;color:var(--muted)}
.studio-hero{border:1px solid var(--acc-line);border-radius:26px;background:var(--studio-hero);min-height:290px;display:grid;grid-template-columns:1.1fr 1fr;overflow:hidden;position:relative}
.hero-copy{padding:35px 36px;position:relative;z-index:1}.hero-label{display:flex;align-items:center;gap:8px;direction:ltr;justify-content:flex-end;font:9px/1.4 var(--mono);letter-spacing:1.8px;color:var(--text2);width:max-content}.hero-label span{width:5px;height:5px;background:var(--acc);border-radius:50%}
.hero-copy h1{font-size:43px;line-height:1.6;letter-spacing:-1.7px;font-weight:850;margin-top:13px}.hero-copy h1 em{font-style:normal;color:var(--acc)}.hero-copy p{font-size:12px;color:var(--text2);line-height:1.95;margin-top:8px}
.hero-models{display:flex;align-items:center;gap:9px;margin-top:21px;font-size:10px;color:var(--text2)}.mini-stack{color:var(--acc);display:grid;place-items:center;width:30px;height:30px;background:var(--acc-soft);border:1px solid var(--acc-line);border-radius:9px}.hero-models button{padding:5px;display:flex;color:var(--acc)}.studio-separator{color:var(--muted);padding-inline:6px}
.hero-art{position:relative;display:flex;align-items:center;justify-content:center;min-width:0;isolation:isolate;overflow:hidden;background:radial-gradient(ellipse at center,var(--studio-tint),transparent 70%)}
.orbit-grid{position:absolute;inset:0;background-image:linear-gradient(var(--line) 1px,transparent 1px),linear-gradient(90deg,var(--line) 1px,transparent 1px);background-size:35px 35px;mask-image:radial-gradient(ellipse,#000,transparent 70%)}
.orbit-ring{position:absolute;border:1px solid var(--acc-line);border-radius:50%;transform:rotate(-28deg);pointer-events:none}.ring-one{width:270px;height:145px;transform:rotate(-35deg)}.ring-two{width:270px;height:145px;transform:rotate(35deg)}.ring-three{width:255px;height:255px;border-style:dashed;opacity:.35;animation:orbit-turn 70s linear infinite}
.orbit-core{width:122px;height:122px;background:var(--studio-tint);border:1px solid var(--acc-line);border-radius:35px;display:grid;place-items:center;transform:rotate(-12deg);box-shadow:inset 0 0 28px var(--acc-soft),0 18px 38px rgba(0,0,0,.08)}.orbit-core span{font-size:84px;color:var(--acc);font-family:Georgia,serif;line-height:1;transform:rotate(12deg)}
.orbit-label{position:absolute;padding:8px 11px;border:1px solid var(--line2);border-radius:10px;background:var(--surface);display:flex;align-items:center;gap:7px;font-size:10px;box-shadow:var(--px-e1)}.orbit-label .px-icon{width:14px;height:14px;color:var(--acc)}.label-one{top:21%;left:12%}.label-two{bottom:18%;right:7%}.orbit-star{position:absolute;color:var(--acc);opacity:.8;font:28px Georgia,serif}.star-one{top:18%;right:16%}.star-two{bottom:23%;left:17%;font-size:20px}.orbit-coordinates{position:absolute;bottom:22px;font:8px var(--mono);letter-spacing:2px;color:var(--muted)}
@keyframes orbit-turn{to{transform:rotate(360deg)}}
.start-box{margin:20px 0 12px;padding:17px 20px 14px;border:1px solid var(--line2);border-radius:20px;background:var(--surface);box-shadow:0 4px 14px rgba(0,0,0,.03);transition:border-color .2s}.start-box:focus-within{border-color:var(--acc)}
.start-box textarea{width:100%;min-height:63px;max-height:180px;resize:vertical;background:none;border:0;outline:none;font-size:13px;line-height:1.9;padding:3px 0 10px}.start-box textarea::placeholder{color:var(--muted)}.start-footer{display:flex;align-items:center;justify-content:space-between;gap:12px}.response-switch{display:flex;align-items:center;gap:3px;border-radius:10px;background:var(--bg2);padding:3px}
.response-mode{display:flex;gap:5px;align-items:center;justify-content:center;min-height:32px;padding:5px 9px;border-radius:7px;font-size:10px;color:var(--muted)}.response-mode.on{background:var(--surface3);color:var(--acc)}.response-mode:hover{color:var(--text)}
.studio-send{display:flex;align-items:center;gap:9px;background:var(--acc);color:var(--bg);font-size:11px;font-weight:650;padding:10px 15px;border-radius:10px;min-height:39px}.studio-send:hover{filter:brightness(1.07)}html[data-px-theme="light"] .studio-send{color:#fff}
.prompt-chips{display:flex;flex-wrap:wrap;gap:7px}.prompt-chips button{display:flex;align-items:center;gap:7px;border:1px solid var(--line);padding:7px 12px;border-radius:999px;color:var(--text2);font-size:10px;background:var(--surface)}.prompt-chips button .px-icon{width:14px;height:14px;color:var(--muted)}.prompt-chips button:hover{border-color:var(--acc-line);color:var(--acc)}
.studio-section-title{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:30px 0 14px}.studio-section-title h3{font-size:14px;font-weight:650}.studio-section-title h2{font-size:25px;font-weight:750;line-height:1.9;letter-spacing:-.5px}.studio-section-title p{font-size:12px;color:var(--text2);margin-top:3px}.studio-section-title button,.studio-status button{display:flex;align-items:center;gap:6px;color:var(--muted);font-size:10px}.studio-section-title button:hover,.studio-status button:hover{color:var(--acc)}.studio-section-title button svg{width:15px;height:15px}
.studio-tools{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.studio-tool{position:relative;display:flex;flex-direction:column;align-items:flex-start;text-align:start;background:var(--surface);border:1px solid var(--line);border-radius:16px;padding:18px 16px;gap:7px;min-height:148px}.studio-tool:hover{transform:translateY(-3px);border-color:var(--acc-line)}.tool-symbol{width:36px;height:36px;display:grid;place-items:center;background:var(--acc-soft);color:var(--acc);border-radius:11px;margin-bottom:5px}.tone-mint .tool-symbol{color:var(--studio-mint);background:color-mix(in srgb,var(--studio-mint) 10%,transparent)}.tone-amber .tool-symbol{color:var(--studio-amber);background:color-mix(in srgb,var(--studio-amber) 10%,transparent)}.tone-coral .tool-symbol{color:var(--studio-coral);background:color-mix(in srgb,var(--studio-coral) 10%,transparent)}.tool-arrow{position:absolute;left:16px;top:22px;color:var(--muted)}.tool-arrow svg{width:15px;height:15px}.studio-tool strong{font-size:12px;font-weight:650}.tool-description{font-size:10px;color:var(--muted);line-height:1.8}
.studio-bottom{display:grid;grid-template-columns:minmax(0,1.65fr) minmax(0,1fr);gap:18px;margin-top:25px}.recent-panel{border:1px solid var(--line);border-radius:20px;padding:6px 20px 15px;background:var(--surface)}.recent-panel .studio-section-title{margin:14px 0}.recent-chat{display:flex;align-items:center;width:100%;gap:12px;padding:13px 0;border-top:1px solid var(--line);text-align:start}.recent-chat:hover .recent-copy strong{color:var(--acc)}.recent-icon{width:32px;height:32px;display:grid;place-items:center;color:var(--muted);border-radius:10px;background:var(--bg2);flex-shrink:0}.recent-icon svg{width:17px;height:17px}.recent-copy{min-width:0;flex:1}.recent-copy strong,.recent-copy small{display:block;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.recent-copy strong{font-size:11px;font-weight:600}.recent-copy small{font-size:10px;color:var(--muted);margin-top:3px}.recent-chat time{font-size:9px;color:var(--muted);white-space:nowrap}.recent-chat>svg{width:15px;height:15px;color:var(--muted)}.studio-empty{display:flex;flex-direction:column;align-items:center;justify-content:center;gap:8px;padding:30px 10px;color:var(--muted)}.studio-empty strong{font-size:12px;color:var(--text2)}.studio-empty p{font-size:10px;line-height:1.8;text-align:center}
.carry-card{border-radius:20px;background:var(--studio-hero);border:1px solid var(--acc-line);padding:22px 25px;position:relative;overflow:hidden}.carry-card .studio-eyebrow{color:var(--acc);font-size:10px}.carry-card h3{font-size:24px;line-height:1.65;letter-spacing:-.6px;margin-top:7px;font-weight:750}.carry-card p{font-size:10px;line-height:1.9;color:var(--text2);max-width:255px;margin-top:10px}.carry-card button{display:flex;align-items:center;gap:9px;font-size:10px;font-weight:600;color:var(--acc);margin-top:15px}.carry-icon{position:absolute;top:25px;left:25px;color:var(--acc)}.carry-icon svg{width:32px;height:32px;opacity:.6}
.studio-status{display:flex;align-items:center;gap:15px;margin:24px 0 4px;padding-top:16px;border-top:1px solid var(--line);color:var(--muted);font-size:9px}.studio-status>span{display:flex;align-items:center;gap:6px}.status-dot{width:5px;height:5px;border-radius:50%;background:var(--muted)}.status-dot.live{background:var(--ok)}.studio-keyhint{margin-inline-start:auto}.studio-keyhint kbd{font:8px var(--mono);border:1px solid var(--line2);border-radius:4px;padding:2px 5px}.studio-onboarding{display:flex;justify-content:space-between;align-items:center;gap:15px;padding:15px 20px;border:1px solid var(--acc-line);border-radius:14px;background:var(--acc-soft);margin-top:20px}.studio-onboarding strong{font-size:12px;margin-inline-start:8px}.studio-onboarding p{font-size:11px;color:var(--text2);margin-top:5px}
/* Portable backup */
.backup-page{max-width:1020px;margin:auto}.backup-page>.studio-section-title{margin:5px 0 27px}.backup-header-icon{display:grid;place-items:center;width:70px;height:70px;background:var(--acc-soft);border:1px solid var(--acc-line);border-radius:21px;color:var(--acc);flex-shrink:0}.backup-grid{display:grid;grid-template-columns:1fr 1fr;gap:20px}.backup-card{border:1px solid var(--line);border-radius:22px;background:var(--surface);padding:26px;min-width:0}.backup-step{font:9px/1.5 var(--mono);color:var(--acc);display:block;margin-bottom:16px}.backup-card h3{font-size:19px;font-weight:700;margin-bottom:7px}.backup-card p{color:var(--text2);font-size:12px;line-height:1.9}.backup-features{display:grid;grid-template-columns:1fr 1fr;gap:14px 8px;margin:25px 0}.backup-features span{display:flex;align-items:center;gap:8px;font-size:10px;color:var(--text2)}.backup-features svg{width:17px;height:17px;color:var(--acc)}.backup-primary{width:100%;min-height:43px;margin-top:9px;display:flex;align-items:center;justify-content:center;gap:9px;font-size:12px;border-radius:12px}
.backup-drop{display:flex;flex-direction:column;align-items:center;text-align:center;justify-content:center;gap:10px;min-height:178px;padding:24px 15px;margin:22px 0 15px;border:1.5px dashed var(--acc-line);border-radius:15px;background:var(--acc-soft);color:var(--acc);cursor:pointer;position:relative}.backup-drop:hover,.backup-drop.dragging{border-color:var(--acc);background:var(--surface2)}.backup-drop strong{font-weight:600;font-size:12px}.backup-drop span{font-size:10px;color:var(--muted)}.backup-drop input{position:absolute;inset:0;opacity:0;width:100%;height:100%;cursor:pointer}.backup-drop:focus-within{outline:2px solid var(--acc);outline-offset:3px}
.backup-note{display:flex;gap:8px;align-items:flex-start;font-size:10px;line-height:1.9;color:var(--muted)}.backup-note svg{width:17px;height:17px;color:var(--ok);margin-top:3px}.backup-inline-status{font-size:11px;color:var(--text2);line-height:1.8;margin-top:12px}.backup-preview{padding:15px;background:var(--bg2);border:1px solid var(--line);border-radius:13px}.backup-preview strong{font-size:12px;color:var(--ok)}.backup-file-name{display:block;direction:ltr;text-align:start;overflow-wrap:anywhere;color:var(--muted);font:10px var(--mono);margin-top:10px}.backup-counts{display:flex;justify-content:space-between;gap:7px;margin:14px 0}.backup-counts span{font-size:10px;color:var(--muted)}.backup-counts b{color:var(--text);font-weight:650;margin-inline-end:3px}.backup-preview p{font-size:10px}.backup-error{font-size:11px;line-height:1.8;color:var(--bad);padding:13px;border:1px solid var(--bad-soft);border-radius:12px;overflow-wrap:anywhere;background:var(--bad-soft)}
.backup-explainer{display:flex;align-items:center;justify-content:center;flex-wrap:wrap;gap:10px;padding:27px 10px}.explainer-number{border:1px solid var(--line2);width:26px;height:26px;border-radius:50%;display:grid;place-items:center;color:var(--acc);font-size:11px}.backup-explainer p{font-size:10px;color:var(--muted);margin-inline-end:12px}.backup-explainer code{color:var(--text);font:10px var(--mono)}.database-card{display:flex;align-items:center;gap:15px;padding:22px;border:1px solid var(--line);border-radius:18px;background:var(--surface);flex-wrap:wrap}.database-symbol{color:var(--acc)}.database-card>div{flex:1;min-width:200px}.database-card h3{font-size:13px}.database-card p{font-size:10px;color:var(--muted);line-height:1.9;margin-top:5px}.database-card .btn{font-size:11px}
/* Chat shares the same colors; the scroller fills the available viewport. */
.main.chat-page{padding:0;overflow:hidden;scrollbar-gutter:auto}.main.chat-page #view{max-width:none;height:100%}.cmain{height:100%;margin:0}.cbar{background:var(--bg2);border-color:var(--line);min-height:57px;padding-inline:20px;gap:9px;flex-wrap:wrap}.cbar select{background:var(--surface);border-color:var(--line);font-size:12px;max-width:280px;min-width:100px;flex:1}.chat-response-switch{margin-inline-start:auto}.cside{background:var(--bg2);border-color:var(--line)}.citem.on{border-color:var(--acc-line)}.cbody{background:var(--bg)}.msgs{padding:26px;gap:22px}.msg{max-width:90%;animation:none}.msg.a .bub{background:var(--surface);border-color:var(--line);border-radius:18px}.msg.u .bub{background:var(--acc-soft);border:1px solid var(--acc-line);color:var(--text);border-radius:18px}.msg .bub{font-size:13px;line-height:1.95;overflow-wrap:anywhere;min-width:0}.msg-av{background:var(--acc-soft);color:var(--acc);box-shadow:none;font-style:normal}.bub pre{direction:ltr;text-align:left;max-width:100%;overflow:auto}.comp{background:var(--bg);padding:14px 22px 10px;border-color:var(--line)}.comp-in{background:var(--surface);border-color:var(--line2);border-radius:16px;padding:8px 10px;gap:10px}.comp-in button#csend{background:var(--acc);color:var(--bg);box-shadow:none;width:38px;height:38px}html[data-px-theme="light"] .comp-in button#csend{color:#fff}.comp-in button#csend.stopping{background:var(--bad-soft);color:var(--bad)}.comp-hint{font-size:9px;margin-top:7px}.chat-welcome{display:flex;flex-direction:column;align-items:center;justify-content:center;flex:1;gap:12px;text-align:center;padding:30px 10px}.chat-welcome-symbol{width:64px;height:64px;display:grid;place-items:center;background:var(--acc-soft);color:var(--acc);border:1px solid var(--acc-line);border-radius:21px}.chat-welcome h2{font-size:21px;font-weight:700}.chat-welcome p{font-size:12px;color:var(--muted);max-width:300px}.chat-welcome .prompt-chips{justify-content:center;margin-top:10px}.stream-note{font-size:10px;color:var(--muted);margin-top:9px}
@media(min-width:961px){.head-menu{display:none}.main{padding-bottom:30px}}
@media(max-width:1100px) and (min-width:961px){.hero-copy{padding:28px}.hero-copy h1{font-size:36px}.studio-tool{padding:15px 12px}.tool-description{font-size:9px}.label-one{left:4%}.label-two{right:3%}}
@media(max-width:960px){.head{padding-inline:18px}.main{padding:22px 20px calc(var(--tab) + var(--safe) + 24px)}.studio-home{max-width:800px}.hero-copy{padding:30px}.hero-copy h1{font-size:38px}.cside{background:var(--bg2)}.head-refresh{display:none}}
@media(max-width:600px){
  :root{--px-head:64px;--px-tab:64px}.head{padding-inline:12px;gap:8px}.head-t h1{font-size:12px}.head-t .sub{font-size:9px}.head-actions{gap:1px}.head .btn-icon{width:33px;height:33px}.head .avbtn{display:none}.main{padding:22px 16px calc(var(--tab) + var(--safe) + 24px)}
  .studio-greeting{margin-bottom:20px}.studio-greeting h2{font-size:14px}.studio-date{display:none}.studio-hero{grid-template-columns:1.12fr 1fr;min-height:255px;border-radius:21px}.hero-copy{padding:23px 20px}.hero-label{font-size:7px;letter-spacing:1px}.hero-copy h1{font-size:28px;line-height:1.75;letter-spacing:-1px;margin-top:14px}.hero-copy p{font-size:10px;line-height:1.95}.hero-models{font-size:8px;gap:5px;margin-top:15px}.hero-models .mini-stack{display:none}.studio-separator{padding-inline:2px}.hero-art{overflow:hidden}.orbit-core{width:81px;height:81px;border-radius:24px}.orbit-core span{font-size:60px}.ring-one,.ring-two{width:185px;height:100px}.ring-three{width:170px;height:170px}.orbit-label{padding:5px 7px;font-size:7px;gap:4px;border-radius:8px}.orbit-label svg{width:11px!important;height:11px!important}.label-one{top:24%;left:7%}.label-two{bottom:21%;right:2%}.orbit-coordinates{font-size:6px;letter-spacing:1px;bottom:17px}.star-one{right:9%;top:19%;font-size:22px}.star-two{left:10%;bottom:20%}
  .start-box{padding:13px 14px 12px;border-radius:17px;margin-top:15px}.start-box textarea{font-size:12px;min-height:64px}.start-footer{gap:8px}.response-mode{font-size:9px;padding:5px 7px;gap:4px;min-height:31px}.response-mode svg{width:12px;height:12px}.studio-send{padding:9px 11px;font-size:10px;gap:5px}.studio-send svg{width:17px;height:17px}.prompt-chips{gap:6px}.prompt-chips button{font-size:9px;padding:6px 9px;gap:5px}.prompt-chips svg{width:12px;height:12px}.studio-section-title{margin-top:25px}.studio-section-title h3{font-size:13px}.studio-section-title button{font-size:9px}.studio-tools{grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}.studio-tool{padding:16px;min-height:142px}.studio-tool strong{font-size:11px}.tool-description{font-size:9px}.studio-bottom{grid-template-columns:1fr;gap:15px;margin-top:20px}.recent-panel{padding-inline:17px}.carry-card{padding:21px}.carry-card h3 br{display:none}.carry-card h3{font-size:22px}.carry-card p{max-width:85%}.studio-status{font-size:8px;gap:12px}.studio-keyhint{display:none!important}.studio-onboarding{align-items:flex-start;flex-direction:column}.studio-onboarding .btn{font-size:11px}
  .backup-page>.studio-section-title{margin-bottom:20px;align-items:flex-start}.studio-section-title h2{font-size:20px}.studio-section-title p{font-size:11px;line-height:1.9}.backup-header-icon{width:48px;height:48px;border-radius:15px}.backup-header-icon svg{width:25px;height:25px}.backup-grid{grid-template-columns:1fr;gap:16px}.backup-card{padding:22px;border-radius:19px}.backup-card h3{font-size:17px}.backup-card p{font-size:11px}.backup-features{margin:22px 0}.backup-explainer{display:grid;grid-template-columns:26px 1fr;justify-content:start;padding-inline:8px;gap:13px}.database-card{padding:18px;gap:10px}.database-card>.btn{flex:1}.database-symbol{display:none}
  .cbar{padding:9px 12px;gap:7px}.cbar select{max-width:none}.chat-response-switch{width:100%;margin:0;justify-content:center;background:none;border-top:1px solid var(--line);padding-top:7px}.msgs{padding:20px 13px;gap:18px}.msg{max-width:96%;gap:7px}.msg .bub{font-size:12px;padding:10px 12px}.msg-av{width:25px;height:25px;border-radius:8px;font-size:11px}.comp{padding:11px 12px 8px}.chat-welcome h2{font-size:18px}.chat-welcome p{font-size:11px}.chat-welcome .prompt-chips{max-width:310px}
}
@media(max-width:360px){.hero-copy{padding:21px 16px}.hero-copy h1{font-size:25px}.hero-art{margin-inline-start:-20px}.hero-models{font-size:7px}.studio-send span{display:none}.head-t .sub{display:none}}
@media(max-width:960px){.tabbar{position:static;inset:auto;width:auto;flex-shrink:0;height:calc(var(--tab) + var(--safe));min-height:calc(var(--tab) + var(--safe));padding-bottom:var(--safe)}.main{padding-bottom:24px}.main.chat-page{padding:0}.cbar{height:auto;flex-shrink:0}}
@media(max-width:600px){.studio-hero{grid-template-columns:1.35fr 1fr}.hero-copy h1{font-size:26px}.hero-copy{padding-inline:20px 14px}.chat-response-switch{flex-shrink:0}}
@media(prefers-reduced-motion:reduce){.orbit-ring{animation:none}.studio-tool:hover{transform:none}}
.head .head-back{flex-shrink:0;color:var(--acc)}.head .head-back[hidden]{display:none}
`;
